### PR TITLE
GH-2: Update linting and add initial CI configs

### PR DESCRIPTION
**Pull request by jobara**
@klown I updated the linting to use [fluid-lint-all](https://www.npmjs.com/package/fluid-lint-all) and added some CI configs to run linting and tests in CI. However, I wasn't able to get the tests to run locally, so CI will likely fail on the tests as well. They fail with the error: "createdb: error: could not connect to database template1: FATAL:  role "admin" does not exist" from ./src/database/scripts/startDockerPostgres.sh

Regarding linting, if you merge this PR I had to fix up some comments and JSDoc. Please review these as I only fixed the errors but didn't make any other changes to the contents, which may need to be updated.

Regarding dependencies, I removed what appeared to be unused dependencies from package.json and updated the others, with the exception of Infusion.

### CODE REVIEW

**Comment by klown** [comment]
Thanks for this, @jobara.  Regarding the `FATAL: role "admin" does not exist ...` error, @cindyli [also noted](https://github.com/fluid-project/preferencesServer/pull/6#issuecomment-797773477) that, which is shame since none of the 259 tests actually ran.  I have a fix, but I'm not going to push it just yet because I think I may have found a related issue where a docker container of the same name is present but stopped.  `docker run` complains of a duplicate name and eventually quits.  I'm thinking of just restarting the container.

**Comment by klown** [comment]
@jobara I've updated my [pull request](https://github.com/fluid-project/preferencesServer/pull/6) with a number of changes.  If it's possible, could you include the changes for just the new linting regime, that would be great.

**Comment by jobara** [comment]
@klown do you want just the new linting infrastructure without the lint fixes?

**Comment by klown** [comment]
> @klown do you want just the new linting infrastructure without the lint fixes?

Yes, please.  I'm assuming that's less work for you, right?

**Comment by jobara** [comment]
@klown yes, it should be less work for me. I'll see if I can get to it today.

**Comment by jobara** [comment]
@klown I rebased from your branch. Other than for the package.json file, if there were conflicts, I just accepted your changes. This means that files that didn't have conflicts will still have their linting updates. Let me know if this work.

**Comment by klown** [comment]
I got these warnings from `npm install`.  Are these something to worry about?  Especially the "You must install peer dependencies yourself".  If so, where are the peer dependencies installed from?

```
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN stylelint-config-standard-scss@1.1.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-standard@18.3.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-recommended@2.2.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by klown** [comment]
There are a number of errors for `.DS_Store`.  I suspect the .gitignore needs an update.

**Comment by jobara** [comment]
> There are a number of errors for `.DS_Store`. I suspect the .gitignore needs an update.

You should probably add `.DS_Store` to your global .gitignore file. After that, you can go through and just delete those files from within this repo's directory structure.

**Comment by jobara** [comment]
> I got these warnings from `npm install`. Are these something to worry about? Especially the "You must install peer dependencies yourself". If so, where are the peer dependencies installed from?
> 
> ```
> npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
> npm WARN stylelint-config-standard-scss@1.1.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN stylelint-config-standard@18.3.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN stylelint-config-recommended@2.2.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
> ```

Unless you're getting errors running the linting, I wouldn't worry about it.

**Comment by klown** [comment]
> > There are a number of errors for `.DS_Store`. I suspect the .gitignore needs an update.
> 
> You should probably add `.DS_Store` to your global .gitignore file. After that, you can go through and just delete those files from within this repo's directory structure.

It turns out that `.DS_Store` was in the project root's `.gitignore` already.  In addition, there are no `.DS_Store` files in the github repository; they are only on my local hard drive.  So, I'm baffled.

**Comment by jobara** [comment]
> It turns out that `.DS_Store` was in the project root's `.gitignore` already. In addition, there are no `.DS_Store` files in the github repository; they are only on my local hard drive. So, I'm baffled.

macOS will generate those files. If you created the repo on your machine they'll be there, so you can just go through and manually delete them.

**Comment by klown** [comment]
Thanks for the help, @jobara.  It made my life easier.

**Pull request merged**
